### ISSUE TITLE
NEED EXE

### ISSUE THREAD

**Issue by NothAmor** [daswareinfach/-DETECTED-Rainbow-Six-Siege-ESP-Hack#1]
I compile display failure...

**Comment by XeroXcs** [comment]
nigger english

**Comment by NothAmor** [comment]
> nigger english

well,sorry for my english but stop using n word,english is not my first language

**Comment by 0x1-1** [comment]
It was detected, the title of the project was organized accordingly. Thank you for your understanding.
RU: Было обнаружено, что название проекта было организовано соответствующим образом. Благодарим вас за понимание.
